Set PlaybackSpeed 1.0
Set TypingSpeed 200ms 
Set Width 950
Set Height 500

Set Shell zsh
Sleep 1s
Type@100ms "mdtt pokemon.md"
Enter
Sleep 500ms
Type "lllhhyypi"
Backspace@100ms 7
Type@100ms  "Raichu"
Ctrl+C
Type "li"
Backspace@100ms 7
Type@100ms "Raichu"
Ctrl+C
Sleep 500ms
Type "jlljljvo"
Escape
Type "gg"
Type "i"
Type@100ms "TYPE 2"
Ctrl+C
Sleep 500ms
Type "G"
Type "G"
Sleep 500ms
Type@100ms "iFlying"
Sleep 500ms
Ctrl+C
Sleep 500ms
Type "q"
Sleep 2s
